import os
import glob
import torch
import numpy as np
import torch.nn.functional as F

# Import your network structure (adjust the import if your file is named differently)
try:
    from training_model import SiameseNetwork
except ImportError:
    from train_model import SiameseNetwork

def load_bin_as_tensor(filepath):
    """
    Reads the raw 3,990-byte Egis hardware dump and prepares it for the AI.
    """
    with open(filepath, 'rb') as f:
        raw = f.read()
        
    if len(raw) != 3990:
        return None
        
    img_np = np.frombuffer(raw, dtype=np.uint8).astype(np.float32)
    img_np = img_np.reshape((57, 70))
    
    # Scale to 0.0 - 1.0 (The absolute values don't matter much anymore due to Z-scoring)
    img_np = img_np / 255.0
        
    INVERT_POLARITY = False
    if INVERT_POLARITY:
        img_np = 1.0 - img_np
        
    tensor = torch.tensor(img_np).unsqueeze(0).unsqueeze(0)
    
    # --- ADD Z-SCORE NORMALIZATION HERE ---
    mean = tensor.mean()
    std = tensor.std()
    tensor = (tensor - mean) / (std + 1e-6)
    # --------------------------------------
    
    return tensor

def run_final_exam():
    device = torch.device("cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu")
    print(f"[*] Validating on device: {device}")

    # Load the model and the trained weights
    net = SiameseNetwork().to(device)
    model_path = "models/siamese_fingerprint.pth"
    
    if not os.path.exists(model_path):
        print(f"[-] ERROR: Model weights not found at {model_path}!")
        return
        
    net.load_state_dict(torch.load(model_path, map_location=device))
    net.eval() # Set model to evaluation mode
    print("[+] Frozen AI Model Loaded Successfully.")

    # Look for the .bin files generated by the harvest script
    dataset_dir = "D:\\GitHub Projects\\EgisTec-EH576\\training_model\\scoofing_data\\raw_fingerprints"
    
    # Explicitly sort the files so 01.bin, 02.bin... are ordered sequentially
    bin_files = sorted(glob.glob(os.path.join(dataset_dir, "*.bin")))
    
    if not bin_files:
        print(f"[-] No .bin files found in '{dataset_dir}'.")
        return

    # Group files by identity assuming naming convention: user1_left_thumb_01.bin
    identities = {}
    for filepath in bin_files:
        filename = os.path.basename(filepath)
        # Split by '_' and assume the last part is the scan number
        parts = filename.replace('.bin', '').split('_')
        identity = "_".join(parts[:-1]) 
        
        if identity not in identities:
            identities[identity] = []
        identities[identity].append(filepath)

    print("\n=== DATASET GROUPING ===")
    for identity, files in identities.items():
        print(f"[*] {identity}: Found {len(files)} sequential scans.")

    print(f"\n[*] Found {len(identities)} unique fingers to test.")

    # Store the generated 128-d embeddings for every file
    embeddings = {}
    with torch.no_grad(): # We don't need to calculate gradients for inference
        for identity, files in identities.items():
            embeddings[identity] = []
            for filepath in files:
                tensor = load_bin_as_tensor(filepath)
                if tensor is not None:
                    tensor = tensor.to(device)
                    # Pass the single image through the network to get the 128-number vector
                    vector = net.forward_once(tensor)
                    embeddings[identity].append(vector)

    print("\n=== HARDWARE VALIDATION RESULTS ===")
    
    match_distances = []
    imposter_distances = []

    for identity, vectors in embeddings.items():
        if len(vectors) < 6:
            continue
            
        # 1. Enrollment Phase: Store the first 5 scans as a gallery of patches (DO NOT AVERAGE)
        enrollment_gallery = vectors[:5] 
        
        # 2. Authentication Phase (Matches): Test remaining scans (06 to 10)
        for live_scan in vectors[5:]:
            # Find the closest matching patch in our enrollment gallery
            distances = [F.pairwise_distance(enrolled, live_scan).item() for enrolled in enrollment_gallery]
            best_match_distance = min(distances)
            match_distances.append(best_match_distance)
            
        # 3. Imposter Phase: Test EVERY OTHER finger against this gallery
        for other_identity, other_vectors in embeddings.items():
            if other_identity == identity:
                continue 
                
            for imposter_scan in other_vectors:
                distances = [F.pairwise_distance(enrolled, imposter_scan).item() for enrolled in enrollment_gallery]
                best_imposter_distance = min(distances)
                imposter_distances.append(best_imposter_distance)

    if not match_distances or not imposter_distances:
        print("[-] Not enough data.")
        return

    avg_match = sum(match_distances) / len(match_distances)
    avg_imposter = sum(imposter_distances) / len(imposter_distances)
    
    print(f"\n[+] Total Valid Logins Tested: {len(match_distances)}")
    print(f"    -> Average Distance for MATCHES:   {avg_match:.4f} (Lower is better)")
    print(f"    -> Max Distance for MATCHES:       {max(match_distances):.4f}")
    
    print(f"\n[+] Total Imposter Attacks Tested: {len(imposter_distances)}")
    print(f"    -> Average Distance for IMPOSTERS: {avg_imposter:.4f} (Higher is better)")
    print(f"    -> Min Distance for IMPOSTERS:     {min(imposter_distances):.4f}")
    
    optimal_threshold = (max(match_distances) + min(imposter_distances)) / 2
    print(f"\n[*] Recommended libfprint Threshold: {optimal_threshold:.4f}")
    
    if max(match_distances) < min(imposter_distances):
        print("\n[SUCCESS] PERFECT SEPARATION! The model can securely authenticate you.")
    else:
        print("\n[WARNING] Overlap detected.")

if __name__ == "__main__":
    run_final_exam()